spring:
  application:
    name: 05_Greet_Service
  boot:
    admin:
      client:
        url: http://localhost:1111/
server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: '*'


